# Generated by Django 5.2.8 on 2025-11-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='basic_salary',
            new_name='base_salary',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='deductions',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='generated_at',
        ),
        migrations.AddField(
            model_name='payroll',
            name='absent_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='leave_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='payroll',
            name='present_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('paid', 'Paid')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
